### ISSUE TITLE
windows authenticated web api call from nodejsclient https

### ISSUE THREAD

**Issue by BilgehanYildiz** [JustinWinthers/ntlm-webapi#2]
I need to call https version of this or how you call https windows authenticated web api from nodejs client can you share example?

**Comment by hlgr360** [comment]
you need to change the user agent to enable https

` HttpsAgent = require('agentkeepalive').HttpsAgent;`
` keepaliveAgent = new HttpsAgent({`

**Comment by JustinWinthers** [comment]
Thank you for your contribution!
